# Generated by Django 3.2.6 on 2021-11-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211031_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
    ]
