# Generated by Django 3.2.6 on 2021-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question_set',
            field=models.IntegerField(default=0),
        ),
    ]
