# Generated by Django 3.2.6 on 2021-11-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_question_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_question',
        ),
        migrations.AlterField(
            model_name='user',
            name='question_set',
            field=models.IntegerField(default=1),
        ),
    ]
