# Generated by Django 3.2.6 on 2021-11-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20211031_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=200)),
                ('option1', models.CharField(default='option1', max_length=100)),
                ('option2', models.CharField(default='option2', max_length=100)),
                ('option3', models.CharField(default='option3', max_length=100)),
                ('option4', models.CharField(default='option4', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('num_pause', models.IntegerField(default=0)),
                ('num_replay', models.IntegerField(default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.actionfiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Guess1_2',
            fields=[
                ('guess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annotation.guess')),
                ('guess', models.CharField(default='', max_length=200)),
            ],
            bases=('annotation.guess',),
        ),
        migrations.CreateModel(
            name='Guess3',
            fields=[
                ('guess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annotation.guess')),
                ('rank1', models.CharField(default='', max_length=200)),
                ('rank2', models.CharField(default='', max_length=200)),
                ('rank3', models.CharField(default='', max_length=200)),
                ('rank4', models.CharField(default='', max_length=200)),
                ('rank5', models.CharField(default='', max_length=200)),
            ],
            bases=('annotation.guess',),
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round1_files', models.ManyToManyField(to='annotation.ActionFiles')),
            ],
        ),
    ]
