# Generated by Django 3.2.6 on 2022-01-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20211112_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionfiles',
            name='person',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
